#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift File.expand_path("../lib", __dir__)
require "pokerogue"

begin
  Pokerogue::CLI.new.start
rescue Interrupt
  puts "\nGame exited."
  exit
end
